let countryCode = {
    "RON" : "RO",
    "USD" : "US",
    "EUR" : "ER",
    "GBP" : "GB",
    "CHF" : "SW",
    "CAD" : "CA",
    "JPY" : "JP",
    "CNY" : "CN",
    "INR" : "IN",
    "RUB" : "RU",
    "BGN" : "BG",
    "CZK" : "CZ",
    "HUF" : "HU",
    "PLN" : "PL",
}
